### ISSUE TITLE
Write documentation for token based authentication

### ISSUE THREAD

**Issue by McPringle** [McPringle/sportchef-server#100]

**Comment by Floxxman** [comment]
Meinst du die Dokumentation im Code oder die technische Doku (tex)?

**Comment by McPringle** [comment]
Technical documentation: ```sportchef_technical_documentation.tex```

**Comment by Floxxman** [comment]
ok, nvm, und #83 ist ein Duplikat?

**Comment by McPringle** [comment]
duplicate of #83
