### ISSUE TITLE
Add AngularJS 2 to the HTML 5 client

### ISSUE THREAD

**Issue by McPringle** [McPringle/sportchef-server#59]
AngularJS 2 is currently available as an alpha preview. This should be okay, because we'll need a few month to implement version 1 of SportChef. While we are working on SportChef, AngularJS 2 should become final and we have a really modern application… ;-)

**Comment by syzer** [comment]
:)

**Comment by McPringle** [comment]
There is a new project for the HTML5 web client: https://github.com/McPringle/sportchef-web
